syntax = "proto2";

import "util.proto";
import "util/net.proto";

package addrman_fuzz;

message Target_data_stream_addr_man {
  required bytes datastream = 1;
  required proto_fuzz_util_net.NetGroupManager netmanager = 2;
}

message Target_addrman {
  required int64 time = 1;
  required proto_fuzz_util_net.NetGroupManager netmanager = 2;
  required proto_fuzz_util_net.AddrManDeterministic addrman = 3;
  required proto_fuzz_util_net.AddrManDeterministic addrman2 = 4;
  optional bytes serialized_datastream = 5;

  message Action {
    message EmptyAction {}
    message AddAddressesAction {
      repeated proto_fuzz_util_net.Address addrs = 1;
      required proto_fuzz_util_net.NetAddress source = 2;
      required uint32 timePenality = 3;
    }
    message GoodAction {
      required proto_fuzz_util_net.Service serviceAddr = 1;
      required uint32 time = 2;
    }
    message AttemptAction {
      required proto_fuzz_util_net.Service serviceAddr = 1;
      required bool count_failure = 2;
      required uint32 time = 3;
    }
    message ConnectedAction {
      required proto_fuzz_util_net.Service serviceAddr = 1;
      required uint32 time = 2;
    }
    message SetServicesAction {
      required proto_fuzz_util_net.Service serviceAddr = 1;
      required proto_fuzz_util.WeakEnum n_service = 2; 
    }

    oneof action_type {
      EmptyAction ResolvConflict = 1;
      EmptyAction SelectTriedCollision = 2;
      AddAddressesAction AddAddresses = 3;
      GoodAction GoodAddress = 4;
      AttemptAction AttemptAddress = 5;
      ConnectedAction ConnectedAddress = 6;
      SetServicesAction SetServices = 7;
    }
  }

  repeated Action actions = 6;
  optional uint32 network = 7;
  required uint32 max_addresses = 8;
  required uint32 max_pct = 9;
  required bool filtered = 10;
  message RepeatableBool {
    required bool value = 1;
  }
  repeated RepeatableBool networklist = 11;
  required bool select_new_only = 12;
  optional bool in_new = 13;
}

message RandAddrMessage {
  required proto_fuzz_util_net.NetAddress address = 1;
}

message FillAddrManMessage {
  required uint32 fraction = 1;

  message SourceLoop {
    required RandAddrMessage sourceAddr = 1;

    message AddressList {
      required RandAddrMessage address = 1;
      required uint32 time_penalty = 2;
      required uint32 isAdd = 3;
    }
    repeated AddressList addresses = 2;
  }
  repeated SourceLoop sources = 2;
}

message Target_addrman_serdeser {
  required int64 time = 1;
  required proto_fuzz_util_net.NetGroupManager netmanager = 2;
  required proto_fuzz_util_net.AddrManDeterministic addrman1 = 3;
  required proto_fuzz_util_net.AddrManDeterministic addrman2 = 4;

  required FillAddrManMessage fillAddrManMessage = 5;
}
