syntax = "proto2";

import "util.proto";

package connect_block_fuzz;

message TxIn {
  // UTXO that is used as a based for this Txin
  oneof base_oneof {
    uint32 baseUTXO = 1;
    uint32 branchUTXO = 2;
  }

  required uint32 nSequence = 3;
  required uint32 prevN = 4;
  required proto_fuzz_util.uint256 prevHash = 5;
  required bytes scriptSig = 6;
  repeated bytes scriptWitness = 7;

  required bool customSequence = 8;
  required bool customPrevN = 9;
  required bool customPrevHash = 10;
  required bool customScriptSig = 11;
  required bool customWitness = 12;
}

message TxOut {
  enum BaseOutputScript {
    BASEOUTPUTSCRIPT_UNSPECIFIED = 0;
    BASEOUTPUTSCRIPT_P2WSH = 1;
    BASEOUTPUTSCRIPT_P2SH = 2;
    BASEOUTPUTSCRIPT_TAPSCRIPT = 3;
    BASEOUTPUTSCRIPT_NOSCRIPT = 4;
  }
  required int64 nValue = 1;
  required BaseOutputScript type = 2;
  required bytes scriptPubKey = 3;
}

message Transaction {
  required bool adjustCoinBase = 1;
  repeated TxIn txIns = 2;
  repeated TxOut txOuts = 3;
}

message Block {
  required int32 nversion = 1;
  required proto_fuzz_util.uint256 hashPrevBlock = 2;
  required proto_fuzz_util.uint256 hashMerkleRoot = 3;
  required uint32 nTime = 4;
  required uint32 nBits = 5;
  required uint32 nNonce = 6;

  required bool adjustVersion = 7;
  required bool adjustBits = 8;
  required bool adjustTime = 9;
  required bool adjustNonce = 10;
  required bool adjustPrevBlock = 11;
  required bool adjustMerkle = 12;
  required bool adjustCoinbaseWitness = 13;

  required Transaction coinbase = 14;
  repeated Transaction txs = 15;
}

message ActivateBestChain {
  repeated Block branch1 = 1;
  repeated Block branch2 = 2;
}
