syntax = "proto2";

import "util.proto";

package script_interpreter_fuzz;

message Target {
  required proto_fuzz_util.CScript script = 1;
  required proto_fuzz_util.CTransaction tx0 = 2;
  required proto_fuzz_util.CTransaction tx1 = 3;
  required uint32 targetInput = 4;
  required int32 typeHash0 = 5;
  required int32 typeHash1 = 6;
  required uint64 amount0 = 7;
  required uint64 amount1 = 8;
  required bool isWitness0 = 9;
  required bool isWitness1 = 10;

  required bytes castToBool = 11;
}
