syntax = "proto3";

package proto_fuzz_util;

message uint256 {
  bytes value = 1;
}

message WeakEnum {
  oneof type {
    uint32 InsideEnum = 1;
    uint32 RawValueEnum = 2;
  }
}

message CtxOut {
  int64 amount = 1;
  bytes scriptPubKey = 2;
}

message CtxIn {
  uint32 nSequence = 3;
  uint32 prevN = 4;
  uint256 prevHash = 5;
  bytes scriptSig = 6;
  repeated bytes scriptWitness = 7;
}

message CTransaction {
  uint32 version = 1;
  uint32 nLockTime = 2;

  repeated CtxIn inputs = 3;
  repeated CtxOut outputs = 4;
}
