syntax = "proto2";

package proto_fuzz_util;

message uint256 {
  required bytes value = 1;
}

message WeakEnum {
  oneof type {
    uint32 InsideEnum = 1;
    uint32 RawValueEnum = 2;
  }
}

message CSimpleTxOut {
  required int64 amount = 1;
  required bytes scriptPubKey = 2;
}

message COutPoint {
  required uint32 prevN = 1;
  required uint256 prevHash = 2;
}

message CSimpleTxIn {
  required COutPoint outPoint = 1;
  required bytes scriptSig = 2;
  repeated bytes scriptWitness = 3;
  required uint32 nSequence = 4;
}

message CSimpleTransaction {
  required uint32 version = 1;
  required uint32 nLockTime = 2;

  repeated CSimpleTxIn inputs = 3;
  repeated CSimpleTxOut outputs = 4;
}

message PublicKey {
  required bytes data = 1;
}

message CScript {
  required bool p2wsh = 1;

  message Element {
    message MultiSigElement {
      required uint32 numSig = 1;
      required uint32 numKey = 2;
      repeated PublicKey pubKeys = 3;
    }

    oneof element_type {
      int64 PushInt64 = 1;
      uint32 Opcode = 2;
      int64 ScriptNum = 3;
      bytes PushByteVector = 4;
      bytes PushMalformatedVector = 5;
      MultiSigElement MultiSig = 6;
    }
  }
  repeated Element elements = 2;
}

message Coin {
  required CSimpleTxOut outIn = 1;
  required int32 nHeightIn = 2;
  required bool fCoinBaseIn = 3;
}

message Sequence {
  oneof seq_type {
    uint32 limited = 1;
    uint32 raw = 2;
  }
}

message CComplexeTransaction {
  message TxInput {
    required uint32 indexTx = 1;
    required uint32 indexTxOut = 2;
    required Sequence sequence = 3;
    message UnlockScript {
      required CScript script = 1;
      repeated bytes scriptWitness = 2;
    }
    optional UnlockScript unlockScript = 4;
  }
  message TxOutput {
    required uint64 amount = 1;
    optional CScript script = 2;
  }
  optional uint32 version = 1;
  required uint32 nLockTime = 2;
  repeated TxInput inputs = 3;
  repeated TxOutput outputs = 4;
}
